// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMS.BusinessObjects.Models;

public partial class SalesOrderItem
{
    public int SalesOrderItemId { get; set; }

    public int? SalesOrderId { get; set; }

    public int? ProductId { get; set; }

    public int Quantity { get; set; }

    public decimal UnitPrice { get; set; }

    public decimal? TotalPrice { get; set; }

    public virtual Product Product { get; set; }

    public virtual SalesOrder SalesOrder { get; set; }
}